apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: app-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python-container
          image: ImageName
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-service"

---
apiVersion: v1
kind: Service
metadata:
  name: app-python-service
spec:
  type: LoadBalancer
  selector:
    app: app-python
  ports:
    - port: 80
      targetPort: 5000