spring:
  application:
    name: redis-challenge
  redis:
    host: your-redis-endpoint.amazonaws.com #adicionar host do redis
    port: 6379
    timeout: 5000
  cache:
    type: redis
server:
  port: 8080
